"""Caddy reverse proxy config generator.

Generates a Caddyfile that exposes all enabled services under one
hostname. Each service is reachable at `<scheme>://<domain>/<svc>/`.

For a `.local` domain, Caddy serves plain HTTP (Caddy will not request
Let's Encrypt for `.local` hostnames). For a public domain, Caddy will
automatically request a Let's Encrypt cert on first request, provided
ports 80/443 are reachable from the internet.
"""

from __future__ import annotations

from pathlib import Path

INSTALL_DIR = Path.home() / "mediahub"
CADDY_CONFIG_DIR = INSTALL_DIR / "config" / "caddy"


# (service_key, route_path, internal_host, internal_port)
DEFAULT_ROUTES: list[tuple[str, str, str, int]] = [
    ("sonarr", "/sonarr", "sonarr", 8989),
    ("radarr", "/radarr", "radarr", 7878),
    ("prowlarr", "/prowlarr", "prowlarr", 9696),
    ("qbittorrent", "/qbittorrent", "qbittorrent", 8080),
    ("jellyfin", "/jellyfin", "jellyfin", 8096),
    ("jellyseerr", "/jellyseerr", "jellyseerr", 5055),
    ("bazarr", "/bazarr", "bazarr", 6767),
    ("notifiarr", "/notifiarr", "notifiarr", 5454),
    ("flaresolverr", "/flaresolverr", "flaresolverr", 8191),
]


def render_caddyfile(*, domain: str, enabled: list[str], ports: dict[str, int]) -> Path:
    """Write the Caddyfile under ~/mediahub/config/caddy/."""
    CADDY_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # For all routes whose service key is core ("sonarr"/"radarr"/...) or
    # whose key is in `enabled`, emit a reverse-proxy stanza.
    always_on = {"sonarr", "radarr", "prowlarr", "qbittorrent"}
    active_routes = [
        (key, path, host, port)
        for key, path, host, port in DEFAULT_ROUTES
        if key in always_on or key in enabled
    ]

    is_local = domain.endswith(".local") or domain in ("localhost", "127.0.0.1")
    site_address = f"http://{domain}" if is_local else domain

    lines: list[str] = [
        "# Caddyfile — generated by mediahub-setup",
        "# Reload with: docker exec mediahub-caddy caddy reload --config /etc/caddy/Caddyfile",
        "",
        f"{site_address} {{",
    ]
    for key, path, host, port in active_routes:
        # Use port from settings if user overrode the internal default
        internal_port = ports.get(key, port) if not key.startswith("qbit") else port
        lines.append(f"    handle_path {path}/* {{")
        lines.append(f"        reverse_proxy {host}:{internal_port}")
        lines.append("    }")
    lines.append("")
    lines.append("    # Redirect bare hostname to Jellyseerr if installed, else Sonarr.")
    lines.append("    handle / {")
    landing = "/jellyseerr/" if "jellyseerr" in enabled else "/sonarr/"
    lines.append(f"        redir {landing} permanent")
    lines.append("    }")
    lines.append("}")

    caddyfile = CADDY_CONFIG_DIR / "Caddyfile"
    caddyfile.write_text("\n".join(lines) + "\n")
    return caddyfile
