"""Notifiarr config + Sonarr/Radarr Connect wiring.

Notifiarr is a notification router: receives webhook events from Sonarr,
Radarr, qBittorrent, etc., and forwards them to configured channels
(Telegram, Discord, Slack, ntfy, …).

Setup flow:
  1. Render a notifiarr.conf TOML file with Telegram credentials.
  2. Add Notifiarr as a Connect/Notification target in Sonarr + Radarr
     (so download/import/grab events fire to Notifiarr's webhook).
  3. Restart the Notifiarr container so it picks up the new config.

The user only needs to provide:
  - Telegram bot token (from @BotFather)
  - Telegram chat ID  (from @userinfobot)

If both are blank, the config still gets written but the Telegram block
is omitted — the user can edit ~/mediahub/config/notifiarr/notifiarr.conf
manually later.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .arr_client import RadarrClient, SonarrClient

INSTALL_DIR = Path.home() / "mediahub"
NOTIFIARR_CONFIG_DIR = INSTALL_DIR / "config" / "notifiarr"
NOTIFIARR_CONTAINER = "mediahub-notifiarr"


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------


def render_notifiarr_config(
    *,
    ports: dict,
    api_keys: dict[str, str],
    shared_password: str,
    telegram_bot_token: str = "",
    telegram_chat_id: str = "",
) -> str:
    """Build the notifiarr.conf TOML string."""
    sonarr_key = api_keys.get("sonarr", "")
    radarr_key = api_keys.get("radarr", "")
    qb_port = ports.get("qbittorrent_web", 8080)

    lines: list[str] = [
        "# notifiarr.conf — generated by mediahub-setup",
        "# https://notifiarr.wiki",
        "",
        "bind_addr = '0.0.0.0:5454'",
        f"ui_password = 'admin:{shared_password}'",
        "log_file = '/config/notifiarr.log'",
        "log_files = 10",
        "log_file_mb = 100",
        "quiet = false",
        "debug = false",
        "",
        "[apps]",
        "",
    ]

    if sonarr_key:
        lines += [
            "[[apps.sonarr]]",
            "name = 'Sonarr'",
            "url = 'http://sonarr:8989'",
            f"api_key = '{sonarr_key}'",
            "interval = '5m'",
            "timeout = '1m'",
            "",
        ]

    if radarr_key:
        lines += [
            "[[apps.radarr]]",
            "name = 'Radarr'",
            "url = 'http://radarr:7878'",
            f"api_key = '{radarr_key}'",
            "interval = '5m'",
            "timeout = '1m'",
            "",
        ]

    lines += [
        "[[apps.qbit]]",
        "name = 'qBittorrent'",
        f"url = 'http://qbittorrent:{qb_port}'",
        "user = 'admin'",
        f"pass = '{shared_password}'",
        "interval = '5m'",
        "timeout = '1m'",
        "",
        "[snapshot]",
        "interval = '0'",
        "",
    ]

    if telegram_bot_token and telegram_chat_id:
        lines += [
            "# ----------------------------------------------------------------",
            "# Telegram routing",
            "# ----------------------------------------------------------------",
            "[[endpoints.url]]",
            "name = 'telegram-downloads'",
            f"url = 'https://api.telegram.org/bot{telegram_bot_token}/sendMessage'",
            "method = 'POST'",
            "content_type = 'application/json'",
            "template = '''",
            "{",
            f'  "chat_id": "{telegram_chat_id}",',
            '  "parse_mode": "HTML",',
            (
                '  "text": "<b>{{.Event.Type}}</b>'
                "\\n{{ if .Event.Title }}{{ .Event.Title }}{{ end }}"
                '\\n{{ if .Event.Subtitle }}{{ .Event.Subtitle }}{{ end }}"'
            ),
            "}",
            "'''",
            "",
        ]

    return "\n".join(lines) + "\n"


def configure_notifiarr_telegram(
    *,
    ports: dict,
    api_keys: dict[str, str],
    shared_password: str,
    telegram_bot_token: str = "",
    telegram_chat_id: str = "",
) -> Path:
    """Write notifiarr.conf and restart the container so it picks it up."""
    NOTIFIARR_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    conf_path = NOTIFIARR_CONFIG_DIR / "notifiarr.conf"
    conf_path.write_text(
        render_notifiarr_config(
            ports=ports,
            api_keys=api_keys,
            shared_password=shared_password,
            telegram_bot_token=telegram_bot_token,
            telegram_chat_id=telegram_chat_id,
        )
    )
    # Best-effort restart so the new config is picked up. Non-fatal if it
    # fails (the user can `docker restart mediahub-notifiarr` manually).
    try:
        subprocess.run(
            ["docker", "restart", NOTIFIARR_CONTAINER],
            capture_output=True,
            timeout=30,
            check=False,
        )
    except Exception:
        pass
    return conf_path


# ---------------------------------------------------------------------------
# Sonarr / Radarr Connect wiring
# ---------------------------------------------------------------------------


def wire_notifiarr_to_arr(
    *,
    sonarr: SonarrClient,
    radarr: RadarrClient,
    notifiarr_internal_url: str,
) -> None:
    """Add Notifiarr as a Webhook notification target in both Sonarr and Radarr.

    Idempotent — skips if a notification with the same name already exists.
    """
    _add_webhook_notification(
        sonarr,
        name="Notifiarr",
        url=f"{notifiarr_internal_url}/api/v1/notification/{{api_key}}",
        # Sonarr-specific event flags
        on_grab=True,
        on_download=True,
        on_upgrade=True,
        on_rename=False,
        on_series_delete=False,
        on_episode_file_delete=False,
        on_episode_file_delete_for_upgrade=False,
        on_health_issue=True,
        on_application_update=False,
        on_manual_interaction_required=True,
    )
    _add_webhook_notification(
        radarr,
        name="Notifiarr",
        url=f"{notifiarr_internal_url}/api/v1/notification/{{api_key}}",
        on_grab=True,
        on_download=True,
        on_upgrade=True,
        on_rename=False,
        on_movie_delete=False,
        on_movie_file_delete=False,
        on_movie_file_delete_for_upgrade=False,
        on_health_issue=True,
        on_application_update=False,
        on_manual_interaction_required=True,
    )


def _add_webhook_notification(client, *, name: str, url: str, **flags: bool) -> dict:
    """Add a webhook-implementation Notification (idempotent) to an *arr instance."""
    api_base = "/api/v3/notification"
    existing = client.get(api_base)
    for n in existing:
        if n.get("name", "").lower() == name.lower():
            return n  # already present

    payload = {
        "name": name,
        "implementation": "Webhook",
        "implementationName": "Webhook",
        "configContract": "WebhookSettings",
        "tags": [],
        "fields": [
            {"name": "url", "value": url},
            {"name": "method", "value": 1},  # 1=POST
            {"name": "username", "value": ""},
            {"name": "password", "value": ""},
        ],
        # Event triggers (all defaulted False then overridden by **flags)
        "onGrab": False,
        "onDownload": False,
        "onUpgrade": False,
        "onRename": False,
        "onSeriesDelete": False,
        "onEpisodeFileDelete": False,
        "onEpisodeFileDeleteForUpgrade": False,
        "onMovieDelete": False,
        "onMovieFileDelete": False,
        "onMovieFileDeleteForUpgrade": False,
        "onHealthIssue": False,
        "onApplicationUpdate": False,
        "onManualInteractionRequired": False,
        "includeHealthWarnings": False,
        "supportsOnGrab": True,
        "supportsOnDownload": True,
        "supportsOnUpgrade": True,
        "supportsOnRename": True,
        "supportsOnSeriesDelete": True,
        "supportsOnEpisodeFileDelete": True,
        "supportsOnEpisodeFileDeleteForUpgrade": True,
        "supportsOnMovieDelete": True,
        "supportsOnMovieFileDelete": True,
        "supportsOnMovieFileDeleteForUpgrade": True,
        "supportsOnHealthIssue": True,
        "supportsOnApplicationUpdate": True,
        "supportsOnManualInteractionRequired": True,
    }
    # Apply caller-provided event flags (key → camelCase)
    flag_map = {
        "on_grab": "onGrab",
        "on_download": "onDownload",
        "on_upgrade": "onUpgrade",
        "on_rename": "onRename",
        "on_series_delete": "onSeriesDelete",
        "on_episode_file_delete": "onEpisodeFileDelete",
        "on_episode_file_delete_for_upgrade": "onEpisodeFileDeleteForUpgrade",
        "on_movie_delete": "onMovieDelete",
        "on_movie_file_delete": "onMovieFileDelete",
        "on_movie_file_delete_for_upgrade": "onMovieFileDeleteForUpgrade",
        "on_health_issue": "onHealthIssue",
        "on_application_update": "onApplicationUpdate",
        "on_manual_interaction_required": "onManualInteractionRequired",
    }
    for k, v in flags.items():
        camel = flag_map.get(k)
        if camel:
            payload[camel] = bool(v)

    return client.post(api_base, payload)
