"""Recyclarr config generator.

Recyclarr syncs quality profiles, formats, and naming conventions from
the TRaSH Guides (https://trash-guides.info/) into Sonarr and Radarr.

The user picks which profiles to sync in the Settings step. We always
include the quality-definition baseline (file-size thresholds per
resolution) and append the user's chosen quality-profile + custom-format
pair for each *arr.

The generated file lives at ``~/mediahub/config/recyclarr/recyclarr.yml``;
the user can edit it freely after the wizard finishes.
"""

from __future__ import annotations

from pathlib import Path
from typing import TypedDict

INSTALL_DIR = Path.home() / "mediahub"
RECYCLARR_CONFIG_DIR = INSTALL_DIR / "config" / "recyclarr"


class RecyclarrProfile(TypedDict):
    name: str  # Human-readable label for the form
    description: str  # One-line explanation
    quality_profile_template: str  # Recyclarr `include:` template key
    custom_formats_template: str  # Companion CF template key


# ---------------------------------------------------------------------------
# Profile catalogues
# ---------------------------------------------------------------------------

SONARR_PROFILES: dict[str, RecyclarrProfile] = {
    "web-1080p": {
        "name": "WEB-DL 1080p",
        "description": "Streaming-quality 1080p — best balance of size and quality",
        "quality_profile_template": "sonarr-v4-quality-profile-web-1080p",
        "custom_formats_template": "sonarr-v4-custom-formats-web-1080p",
    },
    "web-2160p": {
        "name": "WEB-DL 2160p (4K)",
        "description": "4K streaming-quality — large files (~25 GB per episode)",
        "quality_profile_template": "sonarr-v4-quality-profile-web-2160p",
        "custom_formats_template": "sonarr-v4-custom-formats-web-2160p",
    },
    "remux-web-1080p": {
        "name": "Remux + WEB 1080p",
        "description": "Bluray remux when available, WEB-DL fallback — premium quality",
        "quality_profile_template": "sonarr-v4-quality-profile-remux-web-1080p",
        "custom_formats_template": "sonarr-v4-custom-formats-remux-web-1080p",
    },
    "anime": {
        "name": "Anime",
        "description": "Tuned for anime release-group conventions",
        "quality_profile_template": "sonarr-v4-quality-profile-anime",
        "custom_formats_template": "sonarr-v4-custom-formats-anime",
    },
}

RADARR_PROFILES: dict[str, RecyclarrProfile] = {
    "hd-bluray-web": {
        "name": "HD Bluray + WEB",
        "description": "1080p Bluray when available, WEB-DL fallback — TRaSH default",
        "quality_profile_template": "radarr-quality-profile-hd-bluray-web",
        "custom_formats_template": "radarr-custom-formats-hd-bluray-web",
    },
    "uhd-bluray-web": {
        "name": "UHD Bluray + WEB (4K)",
        "description": "2160p Bluray + WEB-DL — for 4K libraries",
        "quality_profile_template": "radarr-quality-profile-uhd-bluray-web",
        "custom_formats_template": "radarr-custom-formats-uhd-bluray-web",
    },
    "remux-web-1080p": {
        "name": "Remux + WEB 1080p",
        "description": "Bluray remux preferred, WEB-DL fallback — premium quality",
        "quality_profile_template": "radarr-quality-profile-remux-web-1080p",
        "custom_formats_template": "radarr-custom-formats-remux-web-1080p",
    },
    "anime": {
        "name": "Anime",
        "description": "Tuned for anime release-group conventions",
        "quality_profile_template": "radarr-quality-profile-anime",
        "custom_formats_template": "radarr-custom-formats-anime",
    },
}


def default_recyclarr_profiles() -> dict[str, list[str]]:
    """Selection used when the user hasn't picked anything yet."""
    return {"sonarr": ["web-1080p"], "radarr": ["hd-bluray-web"]}


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------


def _render_includes(profiles: dict[str, RecyclarrProfile], keys: list[str]) -> list[str]:
    out: list[str] = []
    for key in keys:
        profile = profiles.get(key)
        if not profile:
            continue
        out.append(f"      - template: {profile['quality_profile_template']}")
        out.append(f"      - template: {profile['custom_formats_template']}")
    return out


def render_recyclarr_config(
    *,
    sonarr_internal_url: str,
    sonarr_api_key: str,
    radarr_internal_url: str,
    radarr_api_key: str,
    selected_profiles: dict[str, list[str]] | None = None,
) -> Path:
    """Write ``recyclarr.yml`` under ``~/mediahub/config/recyclarr/``.

    ``selected_profiles`` is ``{"sonarr": [keys…], "radarr": [keys…]}``.
    When None, falls back to :func:`default_recyclarr_profiles`.
    """
    selected = selected_profiles or default_recyclarr_profiles()
    sonarr_keys = selected.get("sonarr") or []
    radarr_keys = selected.get("radarr") or []

    lines: list[str] = [
        "# recyclarr.yml — generated by mediahub-setup",
        "# Edit freely; see https://recyclarr.dev/wiki/yaml/config-reference/",
        "# `recyclarr sync` runs on the cron schedule defined in docker-compose.yml.",
        "",
        "sonarr:",
        "  series:",
        f"    base_url: {sonarr_internal_url}",
        f"    api_key: {sonarr_api_key}",
        "",
        "    include:",
        "      - template: sonarr-quality-definition-series",
        *_render_includes(SONARR_PROFILES, sonarr_keys),
        "",
        "radarr:",
        "  movies:",
        f"    base_url: {radarr_internal_url}",
        f"    api_key: {radarr_api_key}",
        "",
        "    include:",
        "      - template: radarr-quality-definition-movie",
        *_render_includes(RADARR_PROFILES, radarr_keys),
        "",
    ]

    RECYCLARR_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    yml_path = RECYCLARR_CONFIG_DIR / "recyclarr.yml"
    yml_path.write_text("\n".join(lines))
    return yml_path
