"""Recyclarr config generator.

Recyclarr syncs quality profiles, formats, and naming conventions from
the TRaSH Guides (https://trash-guides.info/) into Sonarr and Radarr.

We generate a minimal `recyclarr.yml` that pulls the most popular
opinionated configs:

  - Radarr: HD Bluray + WEB profile + Anime profile
  - Sonarr v4: WEB-1080p profile + Anime profile

The user can extend the file at ~/mediahub/config/recyclarr/recyclarr.yml
to add more profiles. Recyclarr runs on a cron schedule (defined in the
compose file) and applies whatever is in the config.
"""

from __future__ import annotations

from pathlib import Path

INSTALL_DIR = Path.home() / "mediahub"
RECYCLARR_CONFIG_DIR = INSTALL_DIR / "config" / "recyclarr"


_RECYCLARR_YML_TEMPLATE = """# recyclarr.yml — generated by mediahub-setup
# Edit freely; see https://recyclarr.dev/wiki/yaml/config-reference/ for the schema.
# `recyclarr sync` runs on the cron schedule defined in docker-compose.yml.

sonarr:
  series:
    base_url: {sonarr_url}
    api_key: {sonarr_api_key}

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

radarr:
  movies:
    base_url: {radarr_url}
    api_key: {radarr_api_key}

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web
"""


def render_recyclarr_config(
    *,
    sonarr_internal_url: str,
    sonarr_api_key: str,
    radarr_internal_url: str,
    radarr_api_key: str,
) -> Path:
    """Write recyclarr.yml under ~/mediahub/config/recyclarr/."""
    RECYCLARR_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    yml_path = RECYCLARR_CONFIG_DIR / "recyclarr.yml"
    yml_path.write_text(
        _RECYCLARR_YML_TEMPLATE.format(
            sonarr_url=sonarr_internal_url,
            sonarr_api_key=sonarr_api_key,
            radarr_url=radarr_internal_url,
            radarr_api_key=radarr_api_key,
        )
    )
    return yml_path
